app/fb/forms.py
from flask.ext.wtf import Form
from wtforms import StringField,SubmitField
from wtforms.validators import Required, Length, Regexp, Optional, NumberRange
from wtforms import ValidationError
from ..models import User


class FollowersForm(Form):
    url_name = StringField('URL Name (e.g. http://www.example.com)',
                validators=[Required()])
    submit = SubmitField('Get Number of Shares')

app/fb/__init__.py
from flask import Blueprint

fb = Blueprint('fb', __name__)

from . import views

app/fb/views.py
# coding: utf-8

from flask import Flask
from flask import g, session, request, url_for, flash
from flask import redirect, render_template
from . import fb
from flask_oauthlib.client import OAuth
from .. import oauth
from flask_oauth import OAuthException
from .forms import FollowersForm
import facebook
from flask import make_response
from flask.ext.login import login_required

facebook = oauth.remote_app('facebook',
    app_key='FACEBOOK'
)

@fb.before_request
def before_request():
    g.user = None
    if 'facebook_oauth' in session:
        g.user = session['facebook_oauth']

@fb.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('fb/index.html')

@fb.route('/number_of_shares', methods=['GET', 'POST'])
@login_required
def number_of_shares():
    if g.user is not None:
        fform = FollowersForm()
	if fform.validate_on_submit():
		url=fform.url_name.data
		q='?ids='+url
		resp = facebook.get(q)
		return render_template('fb/result_shares.html', resp=resp, url=url )
    	return render_template('fb/number_of_shares.html', fform = fform)


@fb.route('/login')
def login():
    callback = url_for(
        'fb.facebook_authorized',
        next=request.args.get('next') or request.referrer or None,
        _external=True
    )
    return facebook.authorize(callback=callback)


@fb.route('/login/authorized')
@facebook.authorized_handler
def facebook_authorized(resp):
    if resp is None:
        flash('Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        ))
    	if isinstance(resp, OAuthException):
        	flash('Access denied: %s' % resp.message)

    else:
    	session['facebook_oauth'] = (resp['access_token'], '')
    return redirect(url_for('fb.index'))

@facebook.tokengetter
def get_facebook_oauth_token():
    return session.get('facebook_oauth')

app/templates/fb/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- {% import '_macros.html' as macros %} -->

{% block title %}DD-CSS - Facebook{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Facebook Data Collection and Analysis</h1>
</div>

<div class="row">
 <div class="col-md-6">
  <div class="panel panel-info">
     <div class="panel-heading">Collect Facebook Data</div>
    <div class="list-group">
       <a href="{{ url_for('fb.number_of_shares') }}" class="list-group-item">
         <h4 class="list-group-item-heading">Get Number Of Shares For a URL</h4>
         <p class="list-group-item-text">You can get it easily by the url</p>
       </a>
       <a href="#" class="list-group-item disabled">
         <h4 class="list-group-item-heading" style="color: #999999">New Features</h4>
         <p class="list-group-item-text">Please contact us and ask for new features</p>
       </a>
    </div>
  </div>
 </div>

 <div class="col-md-6">
  <div class="panel panel-success ">
    <div class="panel-heading">Analyze Facebook Data</div>
    <div class="list-group">
       <a href="#" class="list-group-item">
         <h4 class="list-group-item-heading">Analysis functions will be listed here</h4>
         <p class="list-group-item-text">Application of methods in social network theory and computational linguistics</p>
       </a>
       <a href="#" class="list-group-item disabled">
         <h4 class="list-group-item-heading" style="color: #999999">New Features</h4>
         <p class="list-group-item-text">Please contact us and ask for new features</p>
       </a>
    </div>
  </div>
 </div>
</div>

{% endblock %}

app/templates/fb/number_of_shares.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- {% import '_macros.html' as macros %} -->

{% block title %}DD-CSS - Facebook{% endblock %}

{% block page_content %}
<div class="row centered-form">
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Get IDs of Open Graph Object URLs</h3>
    </div>
    <div class="panel-body">
      {{ wtf.quick_form(fform) }}
    </div>
</div>
</div>
{% endblock %}

app/templates/fb/result.html
{% extends "base.html" %}

{% block title %}DD-CSS - Facebook{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Facebook number of shares</h1>
</div>
<div>
<ul>
{% if resp.data[url] is defined %}
	<li>ID: {{ resp.data[url]['id'] }}</li>
	<li>SHARES: {{ resp.data[url]['shares'] }}</li>
{% elif resp.data['error'] is defined %}
	<li>ERROR MESSAGE: {{ resp.data['error']['message'] }}</li>
	<li>ERROR TYPE: {{ resp.data['error']['type'] }}</li>
	<li>ERROR CODE: {{ resp.data['error']['code'] }}</li>
{% else %}
	THERE IS NO FACEBOOK SHARE FOR THIS SITE
</ul>
{% endif %}
</div>
{% endblock %}

app/templates/fb/result_shares.html
{% extends "base.html" %}

{% block title %}DD-CSS - Facebook{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Facebook number of shares</h1>
</div>
<div>
<ul>
{% if resp.data[url] is defined %}
	<li>ID: {{ resp.data[url]['id'] }}</li>
	<li>SHARES: {{ resp.data[url]['shares'] }}</li>
{% elif resp.data['error'] is defined %}
	<li>ERROR MESSAGE: {{ resp.data['error']['message'] }}</li>
	<li>ERROR TYPE: {{ resp.data['error']['type'] }}</li>
	<li>ERROR CODE: {{ resp.data['error']['code'] }}</li>
{% else %}
	THERE IS NO FACEBOOK SHARE FOR THIS SITE
</ul>
{% endif %}
</div>
{% endblock %}