app/tw/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, RadioField
from wtforms.validators import Required, Length, Regexp, Optional, NumberRange
from wtforms import ValidationError
from ..models import User


class FollowersForm(Form):
    screen_name = StringField('Screen Name (e.g. tozCSS)',
                validators=[Required(), Length(1, 15), Regexp('[a-zA-Z0-9_]',
                           0, "Not a valid screen name")])
    friends_limit = IntegerField('Friends Limit (default 0)', default = 0,
                    validators=[Optional(),NumberRange(min=0,max=100000000,message="Number of followers should be between 0-100000000")])
    followers_limit = IntegerField('Followers Limit (default 1000)',  default = 1000,
                    validators=[Optional(),NumberRange(min=0,max=100000000,message="Number of followers should be between 0-100000000")])
    submit = SubmitField('Get Friends and/or Followers')


class UserTimelineForm(Form):
    screen_name = StringField('Screen Name (e.g. tozCSS)',
                validators=[Required(), Length(1, 15), Regexp('[a-zA-Z0-9_]',
                           0, "Not a valid screen name")])
    max_results = IntegerField('Max Results (default 1000)',  default = 1000,
                    validators=[Optional(),NumberRange(min=0,max=3200,message="Number of followers should be between 0-3200")])
    submit = SubmitField('Get User\'s Tweets')

class ListMembersForm(Form):
    owner_screen_name = StringField('Owner Screen Name (e.g. gov)',
            validators=[Required(), Length(1, 15), Regexp('[a-zA-Z0-9_]',
                       0, "Not a valid screen name")])
    slug = StringField('Slug (e.g. us-senate)',
                validators=[Required(), Length(1, 50), Regexp('[a-zA-Z0-9_-]',0, "Not a valid slug")])
    submit = SubmitField('Get List Members')

app/tw/__init__.py
from flask import Blueprint

tw = Blueprint('tw', __name__)

from . import views

app/tw/views.py
# coding: utf-8

from flask import Flask, make_response
from flask import g, session, request, url_for, flash
from flask import redirect, render_template
from flask.ext.login import login_required
from flask.ext.login import current_user
from . import tw
from .. import oauth
from .forms import FollowersForm, UserTimelineForm, ListMembersForm
import twitter as t
import json
from functools import partial
import sys
import csv
import io
from collections import defaultdict
from bson.json_util import dumps
from datetime import datetime
from ..util import save_to_mongo
import time
from threading import Thread
from flask import copy_current_request_context

twitter = oauth.remote_app(    
     'twitter',
     app_key='TWITTER'
)

@twitter.tokengetter
def get_twitter_token():
    if 'twitter_oauth' in session:
        resp = session['twitter_oauth']
        return resp['oauth_token'], resp['oauth_token_secret']


@tw.before_request
def before_request():
    g.user = None
    if 'twitter_oauth' in session:
        g.user = session['twitter_oauth']


@tw.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('tw/index.html')


@tw.route('/list-members', methods=['GET', 'POST'])
@login_required
def list_members():
    tweets = None
    if g.user is not None:
        form = ListMembersForm()
        if form.validate_on_submit():
            flash("Your request is received, you can download the results here when its completed")
            
            @copy_current_request_context
            def get_list_members_async(owner_screen_name,slug):
                twitter_api = oauth_login()
                get_list_members(twitter_api,owner_screen_name=owner_screen_name,slug=slug)
            
            thr = Thread(target=get_list_members_async, args=[form.owner_screen_name.data, form.slug.data])
            thr.start()
            return redirect(url_for('main.user', username=current_user.username))
    return render_template('tw/list-members.html', form=form)


def get_list_members(twitter_api,owner_screen_name=None,slug=None):
    # Must have both the owner_screen_name and slug
    assert (owner_screen_name != None) and (slug != None), \
    "Must have owner_screen_name or slug"

    members = []
    #ddcss.queries.ensureIndex( { username: 1 } )
    ff = defaultdict()
    ff['qname'] = 'Twitter List Members'
    ff['created_time'] = datetime.now()
    ff['username'] = current_user.username
    ff['parameters'] = defaultdict()
    ff['parameters']['owner_screen_name'] = owner_screen_name
    ff['parameters']['slug'] = slug
    ff['data'] = []

    #https://dev.twitter.com/rest/reference/get/lists/members
    list_members = partial(make_twitter_request, twitter_api.lists.members, count=5000)
    cursor = -1
    while cursor != 0:
        # Use make_twitter_request via the partially bound callable...
        response = list_members(owner_screen_name=owner_screen_name, slug=slug, cursor=cursor)

        if response is not None:
            ff['data'] += response['users']
            cursor = response['next_cursor']
            id = save_to_mongo(ff,"ddcss","queries")

        print >> sys.stderr, 'Fetched {0} total {1} list members of {2}. next_cursor: {3}'.format(len(ff['data']), 
                                                slug, owner_screen_name, cursor)
# twitter_api = oauth_login()
# res = twitter_api.lists.members(slug='us-senate',owner_screen_name='gov',cursor=-1)
# for user in res['users']:
#     print user['id'],user['screen_name'],user['name'],user['location'],user['created_at'],...


@tw.route('/user-timeline', methods=['GET', 'POST'])
@login_required
def user_timeline():
    tweets = None
    if g.user is not None:
        form = UserTimelineForm()
        if form.validate_on_submit():
            flash("Your request is received, you can download the results here when its completed")
            
            @copy_current_request_context
            def harvest_user_timeline_async(screen_name,max_results):
            	twitter_api = oauth_login()
            	harvest_user_timeline(twitter_api,screen_name=screen_name,max_results=int(max_results))
            
            thr = Thread(target=harvest_user_timeline_async, args=[form.screen_name.data, form.max_results.data])
            thr.start()
            return redirect(url_for('main.user', username=current_user.username))
    return render_template('tw/user-timeline.html', form=form)


def harvest_user_timeline(twitter_api, screen_name=None, user_id=None, max_results=1000):
     
    assert (screen_name != None) != (user_id != None), \
    "Must have screen_name or user_id, but not both"    
    
    ff = defaultdict()
    ff['qname'] = 'Twitter User Timeline'
    ff['created_time'] = datetime.now()
    ff['username'] = current_user.username
    ff['parameters'] = defaultdict()
    ff['parameters']['screen_name'] = screen_name if screen_name else user_id
    ff['parameters']['max_results'] = max_results
    ff['data'] = defaultdict(list)


    kw = {  # Keyword args for the Twitter API call
        'count': 200,
        'trim_user': 'true',
        'include_rts' : 'true',
        'since_id' : 1
        }
    
    if screen_name:
        kw['screen_name'] = screen_name
    else:
        kw['user_id'] = user_id
        
    max_pages = 16
    results = []
    
    tweets = make_twitter_request(twitter_api.statuses.user_timeline, **kw)
    
    if tweets is None: # 401 (Not Authorized) - Need to bail out on loop entry
        tweets = []
        
    results += tweets
    
    print >> sys.stderr, 'Fetched %i tweets' % len(tweets)
    
    page_num = 1
    
    # Many Twitter accounts have fewer than 200 tweets so you don't want to enter
    # the loop and waste a precious request if max_results = 200.
    
    # Note: Analogous optimizations could be applied inside the loop to try and 
    # save requests. e.g. Don't make a third request if you have 287 tweets out of 
    # a possible 400 tweets after your second request. Twitter does do some 
    # post-filtering on censored and deleted tweets out of batches of 'count', though,
    # so you can't strictly check for the number of results being 200. You might get
    # back 198, for example, and still have many more tweets to go. If you have the
    # total number of tweets for an account (by GET /users/lookup/), then you could 
    # simply use this value as a guide.
    
    if max_results == kw['count']:
        page_num = max_pages # Prevent loop entry
    
    while page_num < max_pages and len(tweets) > 0 and len(results) < max_results:
    
        # Necessary for traversing the timeline in Twitter's v1.1 API:
        # get the next query's max-id parameter to pass in.
        # See https://dev.twitter.com/docs/working-with-timelines.
        kw['max_id'] = min([ tweet['id'] for tweet in tweets]) - 1 
    
        tweets = make_twitter_request(twitter_api.statuses.user_timeline, **kw)
        results += tweets
        ff['data'] = results
        id = save_to_mongo(ff,"ddcss","queries")

        print >> sys.stderr, 'Fetched %i tweets' % (len(tweets),)
    
        page_num += 1
        
    print >> sys.stderr, 'Done fetching tweets'
    return results[:max_results]
    


@tw.route('/friends-followers', methods=['GET', 'POST'])
@login_required
def friends_followers():
    tweets = None
    if g.user is not None:
        form = FollowersForm()
        if form.validate_on_submit():
            flash("Your request is received, you can download the results here when its completed")
            
            @copy_current_request_context
            def getFollowers_async(screen_name,friends_limit,followers_limit):
                    getFollowers(screen_name,friends_limit,followers_limit)

            thr = Thread(target=getFollowers_async, args=[form.screen_name.data, form.friends_limit.data, form.followers_limit.data])
            thr.start()
            #res = getFollowers(form.screen_name.data, form.friends_limit.data, form.followers_limit.data)
            return redirect(url_for('main.user', username=current_user.username))
            #response = make_response(res)
            #response.headers["Content-Disposition"] = "attachment; filename=followers.csv"
            #return response #return redirect(request.args.get('next') or url_for('tw.index'))
    return render_template('tw/friends-followers.html', form=form)


@tw.route('/login')
@login_required
def login():
    if g.user is not None:
        return redirect(url_for('tw.index'))
    callback_url = url_for('tw.oauthorized', next=request.args.get('next'))
    return twitter.authorize(callback=callback_url or request.referrer or None)


@tw.route('/logout')
def logout():
    session.pop('twitter_oauth', None)
    return redirect(url_for('tw.index'))


@tw.route('/oauthorized')
@twitter.authorized_handler
def oauthorized(resp):
    if resp is None:
        flash('You denied the request to sign in.')
    else:
        session['twitter_oauth'] = resp
    return redirect(url_for('tw.index'))


def oauth_login():
    tok,tos = get_twitter_token()
    auth = t.oauth.OAuth(tok, tos, twitter.consumer_key, twitter.consumer_secret)
    twitter_api = t.Twitter(auth=auth)
    return twitter_api


def getFollowers(screen_name,friends_limit,followers_limit):
    if int(friends_limit) == 0 and int(followers_limit) == 0:
        flash('At least one of the limits should be greater than zero')
        return redirect(url_for('tw.friends_followers'))
    twitter_api = oauth_login()
    friends_ids, followers_ids = get_friends_followers_ids(twitter_api, screen_name=screen_name, friends_limit=int(friends_limit), followers_limit=int(followers_limit))


def make_twitter_request(twitter_api_func, max_errors=10, *args, **kw): 
    
    # A nested helper function that handles common HTTPErrors. Return an updated
    # value for wait_period if the problem is a 500 level error. Block until the

app/templates/tw/friends-followers.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import '_macros.html' as macros %}

{% block title %}DD-CSS - Twitter{% endblock %}

{% block page_content %}

 {{ macros.form_in_panel(form,"Get IDs of Friends and Followers") }}
 {{ macros.about_in_panel("About",
      "You can download all follower/friend IDs of a tweep",
      "After submitting your request you can get the results immediately,
      or based on your authenticated account status you might have to wait. </p>

      <p> Due to Twitter rate limiting policy (15 API calls per 15 minutes window limit),
      there is no way to fetch all the friends/followers of a user
      that exceeds 75,000 ids (15 times the max amount of ids per cursor [5000]) without having to wait 15 minutes. </p>

      <p> Our database is updated as Twitter allows your account to fetch the remaining follower ids.
      So, if you are collecting 750K ids, you should visit your profile page 150 minutes later to download all.") }}

{% endblock %}

app/templates/tw/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
<!-- {% import '_macros.html' as macros %} -->

{% block title %}DD-CSS - Twitter{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Twitter Data Collection and Analysis</h1>
</div>

<div class="row">
 <div class="col-md-6">
  <div class="panel panel-info">
     <div class="panel-heading">Collect Twitter Data</div>
    <div class="list-group">
       <a href="{{ url_for('tw.friends_followers') }}" class="list-group-item">
         <h4 class="list-group-item-heading">Get IDs of Friends and Followers</h4>
         <p class="list-group-item-text">Download up to 75K IDs in a second to make further analysis</p>
       </a>
      <a href="{{ url_for('tw.user_timeline') }}" class="list-group-item">
         <h4 class="list-group-item-heading">Get Tweets from User Timeline</h4>
         <p class="list-group-item-text">Download up to 3200 last tweets of a user with a single click</p>
       </a>
      <a href="{{ url_for('tw.list_members') }}" class="list-group-item">
         <h4 class="list-group-item-heading">Get Members of a Twitter List</h4>
         <p class="list-group-item-text">Download valuable information about every member of a list</p>
       </a>
       <a href="#" class="list-group-item disabled">
         <h4 class="list-group-item-heading" style="color: #999999">New Features</h4>
         <p class="list-group-item-text">Please contact us and ask for new features</p>
       </a>
    </div>
  </div>
 </div>

 <div class="col-md-6">
  <div class="panel panel-success ">
    <div class="panel-heading">Analyze Twitter Data</div>
    <div class="list-group">
       <a href="#" class="list-group-item">
         <h4 class="list-group-item-heading">Analysis functions will be listed here</h4>
         <p class="list-group-item-text">Application of methods in social network theory and computational linguistics</p>
       </a>
       <a href="#" class="list-group-item disabled">
         <h4 class="list-group-item-heading" style="color: #999999">New Features</h4>
         <p class="list-group-item-text">Please contact us and ask for new features</p>
       </a>
    </div>
  </div>
 </div>
</div>

{% endblock %}

app/templates/tw/list-members.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import '_macros.html' as macros %}

{% block title %}DD-CSS - Twitter{% endblock %}

{% block page_content %}

 {{ macros.form_in_panel(form,"Get Members of a Twitter List") }}
 {{ macros.about_in_panel("About",
      "You can download all the info on the members of a list",
      "Information about the members of a Twitter list available in two formats. CSV files have 
      <i>id, screen_name,name, location, description, created_at, friends_count (followed by), followers_count, statuses_count (tweet + retweet count), favourites_count</i> fields. JSON formatted files contain even more info.
      <p>
      To get it for all 100 of the US senators listed at <a href='https://twitter.com/gov/lists/us-senate/members' target='_blank'>twitter.com/gov/lists/us-senate</a>,
      the text fields should be populated like the examples given in the paranthesis") }}

{% endblock %}

app/templates/tw/user-timeline.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import '_macros.html' as macros %}

{% block title %}DD-CSS - Twitter{% endblock %}

{% block page_content %}

 {{ macros.form_in_panel(form,"Get Tweets from User Timeline") }}
 {{ macros.about_in_panel("About",
      "You can download up to 3200 last tweets of a user",
      "After submitting your request you can get the results immediately,
      or based on your authenticated account status you might have to wait.") }}

{% endblock %}